export const ADD_TO_FAVOURITE_REQUEST = 'ADD_TO_FAVOURITE_REQUEST'
export const ADD_TO_FAVOURITE_SUCCESS = 'ADD_TO_FAVOURITE_SUCCESS'
export const ADD_TO_FAVOURITE_FAIL = 'ADD_TO_FAVOURITE_FAIL'

export const GET_FAVOURITE_REQUEST = 'GET_FAVOURITE_REQUEST'
export const GET_FAVOURITE_SUCCESS = 'GET_FAVOURITE_SUCCESS'
export const GET_FAVOURITE_FAIL = 'GET_FAVOURITE_FAIL'

export const REMOVE_FROM_FAVOURITE_REQUEST = 'REMOVE_FROM_FAVOURITE_REQUEST'
export const REMOVE_FROM_FAVOURITE_SUCCESS = 'REMOVE_FROM_FAVOURITE_SUCCESS'
export const REMOVE_FROM_FAVOURITE_FAIL = 'REMOVE_FROM_FAVOURITE_FAIL'