export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_ALL_PRODUCT_REQUEST = 'GET_ALL_PRODUCT_REQUEST'
export const GET_ALL_PRODUCT_FAIL ='GET_ALL_PRODUCT_FAIL'

export const FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY';